services:
  - type: web
    name: linkedin-automation
    env: node
    buildCommand: npm ci && npx playwright install chromium --with-deps
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
